### ISSUE TITLE
Отсутствует пример кастомного кластера в документации

### ISSUE THREAD

**Issue by SergeyNekrasoff** [yandex-maps-unofficial/vue-yandex-map#157]
Нет примера в документации, как сделать кастомный кластер, добавьте плиз

Пытаюсь изменить шрифт у кластера через свойство clusterContentLayout:

```javascript
clusterOptions: {
        1: {
          clusterDisableClickZoom: false, 
          hasBalloon: false,
          clusterContentLayout: `<div style="color: #FFFFFF; font-weight: bold;">${[properties.iconContent]}</div>`,
          clusterIcons: [
            {
                href: require('assets/svg/marker.svg'),
                size: [40, 49],
                offset: [-20, -25]
            },
            {
                href: require('assets/svg/cluster-map.svg'),
                size: [50, 50],
                offset: [-25, -25]
            }
          ],
          clusterNumbers: [50]
        }
      }
```

**Comment by PNKBizz** [comment]
Пофиксил кластер в доках, спасибо. Надеюсь поможет )

**Comment by SergeyNekrasoff** [comment]
> Пофиксил кластер в доках, спасибо. Надеюсь поможет )

К сожалению кластер не меняется, пробовал как в документации - тоже не работает

```
clusterOptions: {
        1: {
          clusterDisableClickZoom: false, 
          hasBalloon: false,
          clusterLayout: '<div style="color: tomato; font-family: Foros; font-weight: 600;">{{ properties.geoObjects.length }}</div>',
          clusterIcons: [
            {
                href: require('assets/svg/marker.svg'),
                size: [40, 49],
                offset: [-20, -25]
            },
            {
                href: require('assets/svg/cluster-map.svg'),
                size: [50, 50],
                offset: [-25, -25]
            }
          ],
          clusterNumbers: [50]
        }
      }
```

**Comment by PNKBizz** [comment]
Сделайте пример в песочнице

**Comment by SergeyNekrasoff** [comment]
https://codesandbox.io/s/codesandbox-nuxt-1ht4k

**Comment by gkhabada** [comment]
@PNKBizz У меня не работает `gridSize` для кластера. Не знаете в чем может быть проблема? Другие свойства работают.

**Comment by sinneren** [comment]
так же не вижу чтоб работал clusterIconShape

**Comment by spokik** [comment]
У меня работает пример из [доки яндекса](https://yandex.ru/dev/maps/jsbox/2.1/clusterer_custom_icon)
правда в отличии от примера выше я не использую require для картинки, я просто прописываю url.

Но мой запрос чуть иной. В доке яндекса существует [option.presetStorage](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/option.presetStorage.htmll) который можно передать в options.preset и будет нам счастье. Однако пресеты на то и пресеты, что ограничены. Мне нужен конкретный цвет. Насколько я понял  из документации  option.presetStorage является экземпляром класса [util.Storage](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/util.Storage.html)

Собственно мой план добавить и использовать новый объект в presetStorage, однако я не понимаю как могу взаимодействовать с ним в рамках плагина.

Возможно кто-то уже решал подобную задачу? Мне нужен конкретно кастомный цвет иконки кластера с оставшимся счетчиком.

**Comment by spokik** [comment]
Я видимо не правильно пронял апи яндекса. Сейчас разобрался.

Так как у нас есть доступ к ymaps, создаем новый объект примерно таким образом. 
`ymaps.option.presetStorage.add('wtClaster', {
            clusterIconColor: "#7851A9",
            preset: "islands#clusterSvgIcons"
        })`

Передаем в компонент опцию
`<YandexClusterer
          :options="{
            gridSize: 64,
            hasBalloon: false,
            preset: 'wtClaster',
          }"
        >
       ......
        </YandexClusterer>
`

**Comment by daniluk4000** [comment]
Оригинальная проблема исправлена, также кастомные кластеры поддерживаются лучше в 2.0
