### ISSUE TITLE
Не подстраивается под размеры контейнера при его изменении

### ISSUE THREAD

**Issue by 4KDA** [yandex-maps-unofficial/vue-yandex-map#240]
При изменении размера родительского блока не изменяется размер карты. (Изначально все хорошо, проблема при изменении размера вышестоящих блоков)
v0.10.7
![image](https://user-images.githubusercontent.com/38465364/79255165-83ce1b80-7e8e-11ea-84ef-18e1346d59c2.png)

**Comment by PNKBizz** [comment]
Посмотрю в чем может быть проблема

**Comment by NoLimitsStudio** [comment]
Такая же проблема, в ymaps задается стиль с размером, если бы его можно было сделать на в пикселях, а 100%, то проблемы бы не было

**Comment by kashter** [comment]
У яндекс карт слежение за размером контейнера задается опцией autoFitToViewport, если поставить значение always, то это скорее всего решит проблему

Подробнее про это свойство в [доках](https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Map-docpage/)

**Comment by daniluk4000** [comment]
Правильный ответ выше, также можно подписаться на обновления (например, событие resize или ResizeObzerver)

Карта автоматически подстраивается в версии 2.0
