### ISSUE TITLE
Маркеры не реагируют на v-show/v-if

### ISSUE THREAD

**Issue by mityukov** [yandex-maps-unofficial/vue-yandex-map#340]
Здравствуйте, а можно пример как реализовать управление видимостью маркеров?

У меня получается что-то такое:

1.  `v-show` — не работает в принципе
2. `v-if` — учитывается только при загрузке компонента. После этого — как не меняй, все побоку
3. `:properties={"visible": shouldBeVisible}` — тоже не работает почему-то…

**Comment by PNKBizz** [comment]
Добрый день! `v-if` должен работать, проверю

**Comment by Stopy** [comment]
@mityukov можно пример неработающего кода?
