### ISSUE TITLE
Vue 3 

### ISSUE THREAD

**Issue by ulugbek-code** [yandex-maps-unofficial/vue-yandex-map#393]
Can we have clear instruction for setting up yandex map please. I junior dev and very confused to set up map for my project. I am using Option api. My project manager is getting nervous(.

**Comment by elzodxon** [comment]
What is the problem? I think, in documentation, everything is clear.

**Comment by daniluk4000** [comment]
Native Vue 3 support is available in 1.x and 2.x. Also was available in 0.x branch on version 0.12.7
