### ISSUE TITLE
При скролле над картой происходит не zoom, а смещение по оси Y.

### ISSUE THREAD

**Issue by EVOSandru6** [yandex-maps-unofficial/vue-yandex-map#417]
Добрый день!

Использую Nuxt ^2.15.8
При попытке  сролла карта сперванемного смещается и только потом зумируется.
Тем самым нарушается калибровка.

Взят первый пример из документации:
https://vue-yandex-maps.github.io/examples/#%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%80%D0%B0-%D0%BF%D0%BE-%D0%BA%D0%BB%D0%B8%D0%BA%D1%83

Также при наведении на маячок отображается не указательный палец, а ладонь ( как для перетаскивания )
С чем это может быть связано?

**Comment by PNKBizz** [comment]
Добрый день!
Сделайте пример в песочнице
