### ISSUE TITLE
Прорисовка карты при перемещении по координатам в версии для vue3

### ISSUE THREAD

**Issue by deepreshion** [yandex-maps-unofficial/vue-yandex-map#427]
При переходе между геообъектами не прорисовывается карта, пример
https://codesandbox.io/s/summer-cloud-eogco2?file=/src/components/HelloWorld.vue

**Comment by PNKBizz** [comment]
Попробуйте использовать `vue-yandex-maps@beta`

**Comment by deepreshion** [comment]
> Попробуйте использовать `vue-yandex-maps@beta`

Пробовал, такое же поведение карты

**Comment by daniluk4000** [comment]
Должно быть ок в 2.0 vue-yandex-maps. Тут выглядит как баг старых Я.Карт
