### ISSUE TITLE
по поводу searchControl

### ISSUE THREAD

**Issue by orangejuicesalta** [yandex-maps-unofficial/vue-yandex-map#439]
Как добавить event 'resultselect' в searchControl если он уже есть в controls, то есть searchControl уже подефолту есть но к нему нужно добавить 'resultselect'?? Я использую vue-yandex-maps 
onMounted(async () => {
  await loadYmap({ settings, debug: true });
 //здесь нужно добавить resultselect event 
//те мотеды которые предлагает chatGpt не работают:)
});
у меня typescript.

**Comment by PNKBizz** [comment]
Нужен рабочий пример в песочнице или в репе
