### ISSUE TITLE
Сервер не смог обработать запрос

### ISSUE THREAD

**Issue by trawen** [yandex-maps-unofficial/vue-yandex-map#442]
Пробую examples/Nuxt, на попытке ввода адрес в строке поиска вылезает ошибка "Сервер не смог обработать запрос
", да и судя по всему не работает параметр :settiings, в нем задавал свой API ключ, а запрос уходит с непонятноо чьм ключем.

**Comment by PNKBizz** [comment]
Нужен рабочий пример в песочнице или в репе
