### ISSUE TITLE
Баг меток с кастомной иконкой

### ISSUE THREAD

**Issue by sharaputo** [yandex-maps-unofficial/vue-yandex-map#445]
При использовании кастомной иконки для меток, проявляется следующий баг: при масштабировании карты, метки перемещаются, занимая правильные координаты только при самом близком приближении. Этот же баг можно увидеть на странице с примерами, там где используется кастомная иконка для меток: https://vue-yandex-maps.github.io/examples/#%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0

**Comment by PNKBizz** [comment]
Возможно из-за оффсета. Попробуйте поэкспериментировать с настройками иконки. Отпишитесь по результату, пожалуйста

**Comment by sharaputo** [comment]
> Возможно из-за оффсета. Попробуйте поэкспериментировать с настройками иконки. Отпишитесь по результату, пожалуйста

Поиграл со всеми параметрами, пока безрезультатно.

**Comment by daniluk4000** [comment]
В 2.0 доступно кастомное позиционирование с помощью пропса `position`
