### ISSUE TITLE
Нужна помощь с Polyline

### ISSUE THREAD

**Issue by testario** [yandex-maps-unofficial/vue-yandex-map#455]
В Vue 3 пытаюсь создать полилайн через ymap-marker, но падает ошибка r[i] is undefined.
![изображение](https://user-images.githubusercontent.com/52890557/230614705-055b7704-bfb9-4434-b0cb-009a39e4294b.png)
![изображение](https://user-images.githubusercontent.com/52890557/230614761-3b627f27-5da0-4f63-b8e7-ec2178aba070.png)

Подскажите, пожалуйста, как мне быть?

**Comment by PNKBizz** [comment]
Посмотрю на выходных. Попробуйте использовать `beta`-версию. Она легче и более правильная

**Comment by testario** [comment]
@PNKBizz спасибо, попробую
