### ISSUE TITLE
yandex marker иконка v1.x-beta версия

### ISSUE THREAD

**Issue by nurik-nuxt** [yandex-maps-unofficial/vue-yandex-map#464]
В доке нет icon в attribute или вызодные параметры как в версия v0.x

**Comment by mcandylab** [comment]
Тоже не нашел как свой кастомный маркер установить

**Comment by nurik-nuxt** [comment]
Вт, 8 авг. 2023 г. в 00:52, Andrey Abramov ***@***.***>:

**Comment by daniluk4000** [comment]
Бага находится не в том репозитории. В целом исправлено в 2.0
