### ISSUE TITLE
Типизация ymaps

### ISSUE THREAD

**Issue by unn3daby** [yandex-maps-unofficial/vue-yandex-map#466]
Как типизировать ymaps?

**Comment by LiNCH35** [comment]
Мы вот этим пользуемся https://www.npmjs.com/package/@types/yandex-maps

**Comment by daniluk4000** [comment]
И также есть новые официальные типы. Доступны в Я.Картах 3.0 и поставляются из коробки в vue-yandex-maps 2.0
