### ISSUE TITLE
SSR+Quasar(Error 403)

### ISSUE THREAD

**Issue by dmsuh** [yandex-maps-unofficial/vue-yandex-map#472]
GET https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=key&mode=release&coordorder=latlong net::ERR_ABORTED 403 (Forbidden) on 192.168.0.11
![image](https://github.com/PNKBizz/vue-yandex-map/assets/90576894/482c5f48-3ad5-49b5-9465-cbe68b9baf61)
But on localhost all works fine
How resolve this problems?

Settings:
mode ssr
yandex-map drawn only client

**Comment by dmsuh** [comment]
Its a problem node.js server cant get information from json.txt which we are get from getUrl

**Comment by daniluk4000** [comment]
Should work fine in 2.0 version of the lib
