### ISSUE TITLE
Подключение карт

### ISSUE THREAD

**Issue by JordanHit** [yandex-maps-unofficial/vue-yandex-map#479]
Помогите. пожалуйста подключить карту, вроде всё делал по документации, но в итоге просто пустой контейнер
`<div id="test">
        <yandex-map
            :settings="settings"
            :coords="coords"
            :zoom="10"
            @click="onClick"
        >
          <ymap-marker
              :coords="coords"
              marker-id="123"
              hint-content="some hint"
          />
        </yandex-map>
      </div>`
      
      `data() {
    return {
      date: '',
      map: null,
      coords: [
        54.82896654088406,
        39.831893822753904
      ],
      settings: {
        apiKey: 'c0dc75c0-2345-4452-9262-47e82c0147e9',
        lang: 'ru_RU',
        coordorder: 'latlong',
        enterprise: false,
        version: '2.1'
      },
    }
  },`
  
  `methods: {
    onClick(e) {
      this.coords = e.get('coords');
    }
  },`

**Comment by daniluk4000** [comment]
Проверьте настройки ширины и высоты для Карты. Также можно воспользоваться версией 2.х, где есть авто-ресайз
