### ISSUE TITLE
Использование на Nuxt

### ISSUE THREAD

**Issue by ValievE** [yandex-maps-unofficial/vue-yandex-map#487]
Как использовать на NUXT 3? Выдает ошибки, если сделать по текущей документации. В частности при создании файла плагина ругается на Vue.use и тд

**Comment by daniluk4000** [comment]
Доброго дня. Вам в идеале перейти на vue-yandex-maps@2. 

Но если не очень хочется:
- Ставьте последнюю 0.12
- Создайте клиентский плагин (name.client.ts), и там вызывайте `nuxtApp.vueApp.use` вместо Vue.use

Должно прокатить, если установить 0.12.x

**Comment by ValievE** [comment]
Стоит версия 2.1.2, но все равно что-то не получается запустить. Документация я полагаю сильно устарела

**Comment by daniluk4000** [comment]
А если у вас 2.1.2, вы не ту смотрите. Как вы туда попали?) Это не сарказм, мне правда интересно - может, мы где-то забыли обновить ссылки? В npm по идее актуальная

Вот ваша дока: https://yandex-maps-unofficial.github.io/vue-yandex-maps/guide/vue3.html#nuxt-3

**Comment by ValievE** [comment]
при установке через npm ставится 2.1.2

**Comment by daniluk4000** [comment]
Да, а как вы попали на старую документацию?

**Comment by daniluk4000** [comment]
И попробуйте подключить по доке выше, плагины там не нужны, модуль подключаете, настраиваете и всё работает

**Comment by daniluk4000** [comment]
> > Да, а как вы попали на старую документацию?
> 
> Через гугл выдает эту страницу первой ссылкой https://vue-yandex-maps.github.io/guide/, оттуда же и сюда переводит

К сожалению, возможности повлиять на это нет. Актуальная документация:
- В римди данного репозитория
- В npm, как в ридми, так и в ссылках справа
- В закрепленной issue с 2.0 в названии

А через гугл да. Так или иначе, актуальный репозиторий: https://github.com/yandex-maps-unofficial/vue-yandex-maps

Эту ишью я закрываю, если будут проблемки или вопросы - пишите туда в ишью или дискуссии
